on: push
name: Test and Lint

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.4.0
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test
